import type { EditManifest } from '../showreel/manifest';

// Synthetic edit that exercises the devices native-agency does not use:
// pageScroll (tall screenshot, step scroll), deviceZoom (browser shell → push through the screen),
// hoverButton, the blur/stagger text effects and the blurDissolve / crossfade transitions. Preset: snappy.
const A = 'edits/demo-tall';

export const demoTall: EditManifest = {
  id: 'demo-tall',
  client: 'demo',
  fps: 30,
  width: 1920,
  height: 1080,
  brand: {
    bg: '#fcfcf6',
    bgDark: '#111111',
    ink: '#111111',
    inkOnDark: '#ffffff',
    dim: '#7a7a72',
    pending: '#c9c8c3',
    accent: '#033278',
    border: '#e4e4dc',
    fonts: { title: 'Manrope', body: 'Inter', mono: 'JetBrainsMono' },
  },
  preset: 'snappy',
  slides: [
    { id: 'title-blur', device: 'title', text: 'A new website.', effect: 'charBlurIn', hold: 40, camera: false },
    { id: 'hero', device: 'kenBurns', hold: 45, in: { kind: 'flash' }, src: `${A}/hero.png`, from: 1.03, blurIn: 12, camera: { push: 1.08 } },
    {
      id: 'scroll',
      device: 'pageScroll',
      hold: 120,
      in: { kind: 'blurDissolve' },
      src: `${A}/page-full.png`,
      srcWidth: 1440,
      srcHeight: 3230,
      frame: 'browser',
      steps: 'auto',
      camera: false,
    },
    { id: 'title-rise', device: 'title', text: 'Built to convert.', effect: 'wordRise', hold: 36, in: { kind: 'crossfade' }, camera: false },
    {
      id: 'device',
      device: 'deviceZoom',
      hold: 70,
      src: `${A}/careers.png`,
      srcWidth: 2880,
      srcHeight: 11884,
      shell: 'browser',
      zoomAt: 40,
      zoomDur: 10,
      scrollPx: 900,
      out: { kind: 'whip', to: 1.6 },
      camera: false,
    },
    { id: 'title-wipe', device: 'title', text: 'Every page, every screen.', effect: 'maskWipe', hold: 36, dark: true, camera: false },
    {
      id: 'button',
      device: 'hoverButton',
      hold: 45,
      label: 'Book a call',
      fill: '#111111',
      hover: '#033278',
      iconFill: '#033278',
      hoverAt: 14,
      out: { kind: 'blurDissolve' },
      camera: { push: 1.05 },
    },
    {
      id: 'lines',
      device: 'title',
      text: '',
      lines: ['Design.', 'Build.', 'Ship.'],
      effect: 'lineRise',
      fontSize: 110,
      hold: 48,
      in: { kind: 'blurDissolve' },
      out: { kind: 'fadeToBlack' },
      camera: false,
    },
  ],
  tail: 6,
};
